In [1]:
import pandas as pd
df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\backtest\all_stocks.parquet")
pd.set_option('display.max_columns', 100)  # 你可以根据需要调整数字
pd.set_option('display.width', 2000)       # 增加横向宽度

In [3]:
for idx in df.index[:10]:
    print(idx)

0
1
2
3
4
5
6
7
8
9

In [7]:
from jinja2 import Environment, FileSystemLoader

# 假设你的模板路径和数据如下
env = Environment(loader=FileSystemLoader(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\new_engine_starter\src\templates"))
template = env.get_template("strategy_selector.jinja")

stock_selection = {
    "numberOfStocks": 10,
    "selectedIndustries": ["Tech", "Finance"],
    "maxIndustryExposure": 0.3
}
factors = [
    {"name": "momentum", "weight": 0.5, "code": "score = calc_momentum(data)"},
    {"name": "pe_ratio", "weight": 0.5, "code": "score = calc_pe(data)"}
]

rendered_code = template.render(stock_selection=stock_selection, factors=factors)
print(rendered_code)

# 选股参数
number_of_stocks = 10
selected_industries = [

    "Tech",

    "Finance",

]
max_industry_exposure = 0.3

# 因子参数
factors = [

    {
        "name": "momentum",
        "weight": 0.5,
        "code": """score = calc_momentum(data)"""
    },

    {
        "name": "pe_ratio",
        "weight": 0.5,
        "code": """score = calc_pe(data)"""
    },

]

# 选股逻辑示例（可根据实际需求替换）
selected_stocks = []

# 应用因子: momentum
score = calc_momentum(data)

# 应用因子: pe_ratio
score = calc_pe(data)


# 行业筛选与限制（伪代码）
# selected_stocks = [s for s in all_stocks if s.industry in selected_industries]
# 限制每个行业最大持仓比例
# ...（具体逻辑可根据 max_industry_exposure 实现）

# 最终选出 number_of_stocks 个股票
# selected_stocks =

In [8]:
import os
print(os.getcwd())

d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\new_engine_starter\src

In [9]:
print(df.head(10))

         date symbol   open   high    low  close    volume  dividend  split_ratio
0  2025-08-06    XYZ  75.33  76.88  75.33  76.13   6488700       0.0          1.0
1  2025-08-05    XYZ  75.98  76.10  74.01  75.29   7207400       0.0          1.0
2  2025-08-04    XYZ  75.02  76.63  74.42  76.12   6082223       0.0          1.0
3  2025-08-01    XYZ  75.00  75.22  72.98  74.03   8235300       0.0          1.0
4  2025-07-31    XYZ  76.78  78.08  76.00  77.26   6769800       0.0          1.0
5  2025-07-30    XYZ  77.71  78.75  77.05  77.59   7352217       0.0          1.0
6  2025-07-29    XYZ  79.70  81.06  77.64  78.18  10632000       0.0          1.0
7  2025-07-28    XYZ  81.20  82.18  80.36  80.57   9578700       0.0          1.0
8  2025-07-25    XYZ  79.76  81.08  78.93  80.74   6348700       0.0          1.0
9  2025-07-24    XYZ  79.44  81.13  79.31  79.77   9377500       0.0          1.0

In [10]:
df_income = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\zipline-reloaded-Alpha-Deputy\src\zipline\data\bundles\data\data_cache\income_statement.parquet")
print(df_income.head(10))

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\desktop\\practice_dom\\FINSHARK\\Alpha-Deputy\\zipline-reloaded-Alpha-Deputy\\src\\zipline\\data\\bundles\\data\\data_cache\\income_statement.parquet'

In [5]:
import pandas as pd

# 假设 df 有 symbol, date, close 字段
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['symbol', 'date'])

# 计算7日动量（收盘价与7天前的比值）
df['momentum_7'] = df.groupby('symbol')['close'].pct_change(periods=7)

# 判断是否连续7天增长
def is_7_days_up(prices):
    return (prices.diff() > 0).rolling(7).sum() == 7

df['is_7_up'] = df.groupby('symbol')['close'].apply(is_7_days_up).reset_index(level=0, drop=True)

# 筛选出满足条件的股票
selected = df[df['is_7_up'] == True]['symbol'].unique()
print("连续7天增长的股票：", selected)

连续7天增长的股票： ['A' 'AA' 'AAC-WT' ... 'ZY' 'ZYME' 'ZYXI']

In [6]:
print(len(selected))

6677

In [7]:
import pandas as pd
from sqlalchemy import create_engine

# 连接 PostgreSQL
engine = create_engine("postgresql://postgres:wanglihao998734@localhost:5432/Alpha-Deputy")

# 读取 Asset 表
asset_df = pd.read_sql("SELECT symbol FROM asset", engine)
asset_symbols = set(asset_df['symbol'])

# 选股映射
final_selected = [s for s in selected if s in asset_symbols]
print("经过 Asset 映射后最终选股：", final_selected)

经过 Asset 映射后最终选股： ['A', 'AA', 'AAC-WT', 'AACG', 'AACI', 'AACQU', 'AADI', 'AAIC-PB', 'AAIC-PC', 'AAL', 'AAM-PA', 'AAM-PB', 'AAMC', 'AAME', 'AAMI', 'AAN', 'AAOI', 'AAON', 'AAP', 'AAPL', 'AARD', 'AAT', 'AAU', 'AAUC', 'AAWW', 'AB', 'ABAT', 'ABB', 'ABBV', 'ABC', 'ABCB', 'ABCM', 'ABEO', 'ABEV', 'ABG', 'ABIO', 'ABL', 'ABLLL', 'ABLLW', 'ABLV', 'ABM', 'ABMD', 'ABNB', 'ABOS', 'ABR', 'ABR-PD', 'ABR-PE', 'ABR-PF', 'ABSI', 'ABST', 'ABT', 'ABTS', 'ABTX', 'ABUS', 'ABVC', 'ABVE', 'ABVX', 'AC', 'ACA', 'ACAD', 'ACB', 'ACBI', 'ACCD', 'ACCO', 'ACEL', 'ACER', 'ACET', 'ACEVW', 'ACGL', 'ACGLN', 'ACGLO', 'ACGN', 'ACH', 'ACHC', 'ACHL', 'ACHR', 'ACHV', 'ACI', 'ACIC', 'ACIU', 'ACIW', 'ACLS', 'ACLX', 'ACM', 'ACMR', 'ACN', 'ACNB', 'ACNT', 'ACOG', 'ACOR', 'ACR', 'ACR-PC', 'ACR-PD', 'ACRE', 'ACRS', 'ACRV', 'ACST', 'ACT', 'ACTG', 'ACVA', 'ACXP', 'ACY', 'ADAG', 'ADAP', 'ADBE', 'ADC', 'ADC-PA', 'ADCT', 'ADD', 'ADEA', 'ADERW', 'ADES', 'ADEX', 'ADGM', 'ADI', 'ADM', 'ADMA', 'ADMP', 'ADN', 'ADNT', 'ADNWW', 'ADP', 'ADPT', 'ADRT-UN', 'ADS', 'ADSE', 'ADSK', 'ADT', 'ADTH', 'ADTHW', 'ADTN', 'ADUS', 'ADV', 'ADVM', 'ADXN', 'AE', 'AEE', 'AEFC', 'AEG', 'AEHL', 'AEHR', 'AEI', 'AEIS', 'AEL', 'AEL-PA', 'AEL-PB', 'AEM', 'AENT', 'AEO', 'AEON', 'AEP', 'AEPPZ', 'AER', 'AERI', 'AES', 'AESC', 'AESI', 'AEVA', 'AEVAW', 'AEY', 'AEYE', 'AEZS', 'AFBI', 'AFCG', 'AFG', 'AFGB', 'AFGC', 'AFGD', 'AFGE', 'AFIN', 'AFINO', 'AFINP', 'AFL', 'AFMD', 'AFRI', 'AFRIW', 'AFRM', 'AFYA', 'AG', 'AGAE', 'AGBA', 'AGBAW', 'AGCO', 'AGE', 'AGEN', 'AGFS', 'AGFY', 'AGH', 'AGI', 'AGIL', 'AGILW', 'AGIO', 'AGL', 'AGLE', 'AGM', 'AGM-PE', 'AGM-PF', 'AGM-PG', 'AGNC', 'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGO', 'AGR', 'AGRIW', 'AGRO', 'AGRX', 'AGS', 'AGTC', 'AGTI', 'AGX', 'AGYS', 'AHCO', 'AHG', 'AHH', 'AHH-PA', 'AHL-PD', 'AHL-PE', 'AHPAW', 'AHR', 'AHT', 'AHT-PD', 'AHT-PF', 'AHT-PG', 'AHT-PH', 'AHT-PI', 'AI', 'AIC', 'AIFF', 'AIG', 'AIG-PA', 'AIH', 'AIHS', 'AIKI', 'AILEW', 'AIM', 'AIMC', 'AIMD', 'AIN', 'AINC', 'AINV', 'AIR', 'AIRC', 'AIRG', 'AIRJ', 'AIRJW', 'AIRS', 'AIRT', 'AIRTP', 'AISP', 'AISPW', 'AIT', 'AIV', 'AIXI', 'AIZ', 'AIZN', 'AJG', 'AJRD', 'AJX', 'AJXA', 'AKA', 'AKAM', 'AKAN', 'AKBA', 'AKLI', 'AKO-A', 'AKO-B', 'AKR', 'AKRO', 'AKTS', 'AKTX', 'AKU', 'AKUS', 'AKYA', 'AL', 'ALAB', 'ALAC', 'ALAR', 'ALB', 'ALBO', 'ALBT', 'ALC', 'ALCC', 'ALCO', 'ALDX', 'ALE', 'ALEC', 'ALEX', 'ALG', 'ALGM', 'ALGN', 'ALGS', 'ALGT', 'ALHC', 'ALIM', 'ALIT', 'ALJJ', 'ALK', 'ALKS', 'ALKT', 'ALL', 'ALL-PB', 'ALL-PG', 'ALL-PH', 'ALL-PI', 'ALL-PJ', 'ALLE', 'ALLG', 'ALLK', 'ALLO', 'ALLR', 'ALLT', 'ALLY', 'ALNT', 'ALNY', 'ALOT', 'ALPN', 'ALPS', 'ALRM', 'ALSN', 'ALT', 'ALTG', 'ALTI', 'ALTM', 'ALTR', 'ALTUU', 'ALTUW', 'ALUR', 'ALV', 'ALVO', 'ALX', 'ALXN', 'ALXO', 'ALYA', 'ALZN', 'AM', 'AMAL', 'AMAM', 'AMAT', 'AMBA', 'AMBC', 'AMBO', 'AMBP', 'AMC', 'AMCIW', 'AMCR', 'AMCX', 'AMD', 'AME', 'AMED', 'AMEH', 'AMG', 'AMGN', 'AMH', 'AMH-PG', 'AMH-PH', 'AMK', 'AMKR', 'AMLX', 'AMN', 'AMNB', 'AMOT', 'AMOV', 'AMP', 'AMPG', 'AMPGW', 'AMPH', 'AMPL', 'AMPS', 'AMPX-WT', 'AMPY', 'AMR', 'AMRB', 'AMRC', 'AMRK', 'AMRN', 'AMRS', 'AMRX', 'AMSC', 'AMSF', 'AMST', 'AMSWA', 'AMT', 'AMTB', 'AMTI', 'AMTM', 'AMTX', 'AMWD', 'AMWL', 'AMX', 'AMZN', 'AN', 'ANAB', 'ANAT', 'ANDAW', 'ANDE', 'ANET', 'ANF', 'ANGH', 'ANGHW', 'ANGI', 'ANGN', 'ANGO', 'ANIK', 'ANIP', 'ANIX', 'ANNA', 'ANNX', 'ANPA', 'ANPC', 'ANRO', 'ANSCW', 'ANSS', 'ANTM', 'ANTX', 'ANVS', 'ANY', 'AOMR', 'AON', 'AORT', 'AOS', 'AOSL', 'AOUT', 'AP', 'AP-WT', 'APA', 'APAM', 'APCX', 'APCXW', 'APD', 'APE', 'APEI', 'APEN', 'APG', 'APGE', 'APGN', 'APH', 'APLD', 'APLE', 'APLS', 'APLT', 'APM', 'APO', 'APOG', 'APP', 'APPF', 'APPHW', 'APPN', 'APPS', 'APR', 'APRE', 'APRN', 'APT', 'APTO', 'APTS', 'APTV', 'APTV-PA', 'APVO', 'APWC', 'APXTW', 'APYX', 'AQMS', 'AQN', 'AQNB', 'AQNU', 'AQST', 'AQUA', 'AR', 'ARAY', 'ARBB', 'ARBE', 'ARBEW', 'ARBK', 'ARBKL', 'ARC', 'ARCB', 'ARCC', 'ARCE', 'ARCH', 'ARCO', 'ARCT', 'ARD', 'ARDT', 'ARDX', 'ARE', 'AREB', 'AREC', 'AREN', 'ARES', 'ARGD', 'ARGO', 'ARGO-PA', 'ARGX', 'ARHS', 'ARI', 'ARIS', 'ARKO', 'ARKOW', 'ARKR', 'ARL', 'ARLO', 'ARLP', 'ARM', 'ARMK', 'ARMN', 'ARMP', 'ARNA', 'ARNC', 'AROC', 'ARQ', 'ARQQW', 'ARQT', 'ARR', 'ARR-PC', 'ARRY', 'ARTL', 'ARTNA', 'ARTW', 'ARVN', 'ARW', 'ARWR', 'AS', 'ASA', 'ASAI', 'ASAN', 'ASB', 'ASB-PE', 'ASB-PF', 'ASBA', 'ASC', 'ASCBR', 'ASGN', 'ASH', 'ASIX', 'ASLE', 'ASLEW', 'ASLN', 'ASM', 'ASMB', 'ASML', 'ASND', 'ASO', 'ASPI', 'ASPN', 'ASPS', 'ASR', 'ASRT', 'ASRV', 'ASTE', 'ASTH', 'ASTI', 'ASTL', 'ASTLW', 'ASTR', 'ASTS', 'ASTSW', 'ASUR', 'ASX', 'ASYS', 'ATAT', 'ATAX', 'ATC', 'ATCH', 'ATCO', 'ATCO-PH', 'ATCO-PI', 'ATCX', 'ATEC', 'ATEN', 'ATER', 'ATEX', 'ATGE', 'ATH', 'ATH-PA', 'ATH-PB', 'ATH-PC', 'ATH-PD', 'ATH-PE', 'ATHA', 'ATHE', 'ATHM', 'ATHR', 'ATHS', 'ATI', 'ATIF', 'ATKR', 'ATLC', 'ATLCL', 'ATLCP', 'ATLO', 'ATMU', 'ATNF', 'ATNFW', 'ATNI', 'ATNM', 'ATO', 'ATOM', 'ATOS', 'ATPC', 'ATR', 'ATRA', 'ATRC', 'ATRI', 'ATRO', 'ATRS', 'ATSG', 'ATTO', 'ATUS', 'ATVI', 'ATW', 'ATXI', 'ATXS', 'ATY', 'ATYR', 'AU', 'AUB', 'AUBAP', 'AUD', 'AUDC', 'AUID', 'AULT', 'AUR', 'AURA', 'AURCW', 'AUROW', 'AUST', 'AUTL', 'AUUD', 'AUVIP', 'AVA', 'AVAH', 'AVAL', 'AVAV', 'AVB', 'AVBP', 'AVCO', 'AVCT', 'AVD', 'AVDL', 'AVDX', 'AVEO', 'AVGO', 'AVGOP', 'AVGR', 'AVID', 'AVIR', 'AVLR', 'AVNS', 'AVNT', 'AVNW', 'AVO', 'AVPT', 'AVPTW', 'AVRO', 'AVT', 'AVTA', 'AVTE', 'AVTR', 'AVTX', 'AVXL', 'AVY', 'AVYA', 'AWH', 'AWI', 'AWK', 'AWR', 'AWRE', 'AWX', 'AX', 'AXGN', 'AXNX', 'AXON', 'AXP', 'AXR', 'AXS', 'AXS-PE', 'AXSM', 'AXTA', 'AXTI', 'AY', 'AYI', 'AYRO', 'AYTU', 'AYX', 'AZ', 'AZEK', 'AZI', 'AZN', 'AZO', 'AZPN', 'AZRE', 'AZTA', 'AZUL', 'AZYO', 'AZZ', 'BA', 'BABA', 'BAC', 'BAC-PB', 'BAC-PE', 'BAC-PK', 'BAC-PL', 'BAC-PM', 'BAC-PN', 'BAC-PO', 'BAC-PP', 'BAC-PQ', 'BAC-PS', 'BACK', 'BAER', 'BAH', 'BAK', 'BALL', 'BALY', 'BAM', 'BAMH', 'BAMI', 'BAMR', 'BANC', 'BANC-PF', 'BAND', 'BANF', 'BANL', 'BANR', 'BANX', 'BAP', 'BARK', 'BASE', 'BATL', 'BATRA', 'BAX', 'BB', 'BBAI', 'BBAR', 'BBBY', 'BBCP', 'BBD', 'BBDC', 'BBDO', 'BBIO', 'BBLGW', 'BBQ', 'BBSI', 'BBU', 'BBUC', 'BBVA', 'BBW', 'BBWI', 'BBY', 'BC', 'BC-PA', 'BC-PB', 'BC-PC', 'BCAB', 'BCAL', 'BCAN', 'BCAX', 'BCBP', 'BCC', 'BCE', 'BCEI', 'BCEL', 'BCH', 'BCLI', 'BCML', 'BCO', 'BCOR', 'BCOV', 'BCPC', 'BCRX', 'BCS', 'BCSF', 'BCTX', 'BCTXW', 'BCYC', 'BDC', 'BDL', 'BDN', 'BDSX', 'BDTX', 'BDX', 'BDXB', 'BE', 'BEAM', 'BEAT', 'BECN', 'BEDU', 'BEEM', 'BEEMW', 'BEEP', 'BEKE', 'BELFA', 'BELFB', 'BEN', 'BENEU', 'BENEW', 'BEP', 'BEP-PA', 'BEPC', 'BEPH', 'BEPI', 'BERY', 'BEST', 'BETS', 'BF-A', 'BF-B', 'BFAM', 'BFC', 'BFH', 'BFI', 'BFIIW', 'BFLY', 'BFLY-WT', 'BFRG', 'BFS', 'BFS-PE', 'BFST', 'BG', 'BGC', 'BGCP', 'BGFV', 'BGI', 'BGLC', 'BGNE', 'BGRY', 'BGRYW', 'BGSF', 'BH', 'BHAT', 'BHB', 'BHC', 'BHE', 'BHF', 'BHFAL', 'BHFAM', 'BHFAN', 'BHFAO', 'BHFAP', 'BHG', 'BHLB', 'BHM', 'BHP', 'BHR', 'BHR-PB', 'BHR-PD', 'BHRB', 'BHSEU', 'BHSEW', 'BHST', 'BHVN', 'BIDU', 'BIG', 'BIGC', 'BIIB', 'BILL', 'BIO', 'BIOTW', 'BIOX', 'BIP', 'BIP-PA', 'BIP-PB', 'BIPC', 'BIPH', 'BIPI', 'BIRD', 'BIRK', 'BITF', 'BIVI', 'BJ', 'BJRI', 'BK', 'BKCC', 'BKD', 'BKE', 'BKEP', 'BKH', 'BKKT', 'BKNG', 'BKR', 'BKSY', 'BKTI', 'BKU', 'BKV', 'BL', 'BLBD', 'BLBX', 'BLCM', 'BLD', 'BLDE', 'BLDEW', 'BLDP', 'BLDR', 'BLFS', 'BLFY', 'BLI', 'BLIN', 'BLK', 'BLKB', 'BLL', 'BLMN', 'BLND', 'BLNK', 'BLNKW', 'BLRX', 'BLSA', 'BLTE', 'BLU', 'BLUE', 'BLUW', 'BLX', 'BLZE', 'BMA', 'BMBL', 'BMEA', 'BMGL', 'BMI', 'BML-PG', 'BML-PH', 'BML-PJ', 'BML-PL', 'BMNR', 'BMO', 'BMRA', 'BMRC', 'BMRN', 'BMTX', 'BMY', 'BN', 'BNED', 'BNFT', 'BNGOW', 'BNH', 'BNIXR', 'BNJ', 'BNL', 'BNR', 'BNRE', 'BNRE-A', 'BNRG', 'BNS', 'BNSO', 'BNT', 'BNTC', 'BNTX', 'BOAC-UN', 'BOC', 'BOCH', 'BODI', 'BODY', 'BOH', 'BOH-PA', 'BOKF', 'BOMN', 'BOOM', 'BOOT', 'BORR', 'BOSC', 'BOTJ', 'BOW', 'BOWL', 'BOWXU', 'BOX', 'BOXL', 'BP', 'BPFH', 'BPMC', 'BPMP', 'BPOP', 'BPRN', 'BPY', 'BPYPM', 'BPYPN', 'BPYPO', 'BPYPP', 'BPYU', 'BPYUP', 'BR', 'BRAG', 'BRBR', 'BRBS', 'BRC', 'BRCC', 'BRCN', 'BRDG', 'BRDS', 'BREA', 'BRFH', 'BRFS', 'BRID', 'BRK-A', 'BRK-B', 'BRKL', 'BRKR', 'BRKS', 'BRLIR', 'BRLIW', 'BRLS', 'BRLSW', 'BRLT', 'BRMK', 'BRN', 'BRNS', 'BRO', 'BROS', 'BRP', 'BRSL', 'BRSP', 'BRTX', 'BRX', 'BRY', 'BRZE', 'BSAC', 'BSAQ', 'BSBR', 'BSET', 'BSGAR', 'BSGM', 'BSIG', 'BSM', 'BSQR', 'BSRR', 'BSVN', 'BSX', 'BSX-PA', 'BSY', 'BTAI', 'BTB', 'BTBT', 'BTCT', 'BTDR', 'BTE', 'BTG', 'BTI', 'BTMWW', 'BTN', 'BTOG', 'BTSG', 'BTSGU', 'BTTR', 'BTU', 'BTWNU', 'BTX', 'BUD', 'BUR', 'BURL', 'BUSE', 'BV', 'BVFL', 'BVH', 'BVN', 'BVS', 'BVXV', 'BW', 'BW-PA', 'BWA', 'BWACW', 'BWAY', 'BWB', 'BWBBP', 'BWEN', 'BWFG', 'BWIN', 'BWLP', 'BWMN', 'BWMX', 'BWNB', 'BWSN', 'BWXT', 'BX', 'BXC', 'BXMT', 'BXP', 'BXRX', 'BXS', 'BY', 'BYD', 'BYFC', 'BYN-WT', 'BYND', 'BYON', 'BYRN', 'BYSI', 'BYU', 'BZ', 'BZFD', 'BZH', 'BZUN', 'C', 'C-PJ', 'C-PK', 'C-PN', 'CAAP', 'CABA', 'CABO', 'CAC', 'CACC', 'CACI', 'CACO', 'CADE', 'CADE-PA', 'CADL', 'CAE', 'CAG', 'CAH', 'CAJ', 'CAKE', 'CAL', 'CALB', 'CALL', 'CALM', 'CALT', 'CALX', 'CAMT', 'CAN', 'CANF', 'CANG', 'CAPL', 'CAPR', 'CAPT', 'CAPTW', 'CAR', 'CARA', 'CARE', 'CARG', 'CARM', 'CARR', 'CARS', 'CART', 'CARV', 'CASA', 'CASH', 'CASI', 'CASS', 'CASY', 'CAT', 'CATC', 'CATO', 'CATX', 'CATY', 'CAVA', 'CB', 'CBAN', 'CBAT', 'CBAY', 'CBD', 'CBFV', 'CBL', 'CBNA', 'CBNK', 'CBOE', 'CBRE', 'CBRL', 'CBSH', 'CBT', 'CBTX', 'CBU', 'CBUS', 'CBZ', 'CC', 'CCAC', 'CCAP', 'CCB', 'CCBG', 'CCCC', 'CCCM', 'CCCMU', 'CCCS', 'CCEC', 'CCEP', 'CCF', 'CCI', 'CCJ', 'CCK', 'CCL', 'CCLD', 'CCLDO', 'CCLDP', 'CCLP', 'CCMP', 'CCNC', 'CCNE', 'CCNEP', 'CCO', 'CCOI', 'CCRC', 'CCRD', 'CCRN', 'CCS', 'CCSI', 'CCU', 'CCV', 'CCXI', 'CD', 'CDAY', 'CDE', 'CDEV', 'CDLR', 'CDLX', 'CDMO', 'CDNA', 'CDNS', 'CDOR', 'CDP', 'CDR', 'CDR-PB', 'CDR-PC', 'CDRE', 'CDROW', 'CDT', 'CDTG', 'CDTTW', 'CDTX', 'CDW', 'CDXC', 'CDXS', 'CDZI', 'CDZIP', 'CE', 'CEA', 'CEAD', 'CECE', 'CECO', 'CEG', 'CEI', 'CEIX', 'CELC', 'CELH', 'CELU', 'CELUW', 'CELZ', 'CEMI', 'CENN', 'CENQW', 'CENT', 'CENTA', 'CENX', 'CEPU', 'CEQP', 'CERE', 'CERN', 'CERT', 'CET', 'CETX', 'CEVA', 'CF', 'CFB', 'CFBK', 'CFFI', 'CFFN', 'CFFS', 'CFG', 'CFG-PD', 'CFG-PE', 'CFLT', 'CFMS', 'CFR', 'CFR-PB', 'CFRX', 'CFSB', 'CFXA', 'CG', 'CGA', 'CGABL', 'CGAU', 'CGBD', 'CGBDL', 'CGEN', 'CGNT', 'CGNX', 'CGON', 'CGRN', 'CGTL', 'CGTX', 'CHCI', 'CHCO', 'CHCT', 'CHD', 'CHDN', 'CHEF', 'CHEK', 'CHGG', 'CHH', 'CHK', 'CHKEL', 'CHKEW', 'CHKEZ', 'CHKP', 'CHMG', 'CHMI', 'CHMI-PA', 'CHMI-PB', 'CHNG', 'CHNGU', 'CHPT', 'CHR', 'CHRD', 'CHRS', 'CHRW', 'CHS', 'CHSCL', 'CHSCM', 'CHSCN', 'CHSCO', 'CHSCP', 'CHSN', 'CHT', 'CHTR', 'CHUY', 'CHWY', 'CHX', 'CI', 'CIA', 'CIB', 'CIDM', 'CIEN', 'CIFR', 'CIFRW', 'CIG', 'CIGI', 'CIH', 'CIIT', 'CIM', 'CIM-PA', 'CIM-PB', 'CIM-PC', 'CIM-PD', 'CINF', 'CINR', 'CINT', 'CIO', 'CIO-PA', 'CION', 'CIR', 'CIT', 'CIVB', 'CIVI', 'CIX', 'CIXX', 'CJET', 'CJJD', 'CKPT', 'CL', 'CLAR', 'CLB', 'CLBK', 'CLBR-WT', 'CLBT', 'CLCO', 'CLDT', 'CLDT-PA', 'CLDX', 'CLEU', 'CLF', 'CLFD', 'CLGN', 'CLH', 'CLI', 'CLIK', 'CLIR', 'CLLS', 'CLMB', 'CLMT', 'CLNE', 'CLNN', 'CLNNW', 'CLOV', 'CLPR', 'CLPS', 'CLPT', 'CLRB', 'CLRO', 'CLS', 'CLSK', 'CLVRW', 'CLVS', 'CLVT', 'CLW', 'CLX', 'CLXT', 'CM', 'CMA', 'CMAX', 'CMBM', 'CMBT', 'CMCL', 'CMCM', 'CMCO', 'CMCT', 'CMCTP', 'CME', 'CMG', 'CMLF', 'CMLFU', 'CMLS', 'CMMB', 'CMP', 'CMPI', 'CMPO', 'CMPOW', 'CMPR', 'CMPS', 'CMPX', 'CMRE', 'CMRE-PB', 'CMRE-PD', 'CMRX', 'CMS', 'CMS-PC', 'CMSA', 'CMSC', 'CMSD', 'CMT', 'CMTG', 'CMTL', 'CNA', 'CNC', 'CNCE', 'CND', 'CNDT', 'CNEY', 'CNF', 'CNH', 'CNHI', 'CNI', 'CNK', 'CNL', 'CNM', 'CNMD', 'CNNB', 'CNNE', 'CNO', 'CNO-PA', 'CNOB', 'CNOBP', 'CNP', 'CNQ', 'CNR', 'CNS', 'CNSL', 'CNSP', 'CNST', 'CNTA', 'CNTB', 'CNTM', 'CNTX', 'CNVS', 'CNX', 'CNXA', 'CNXC', 'CNXN', 'COCH', 'COCHW', 'COCO', 'CODA', 'CODI', 'CODI-PA', 'CODI-PB', 'CODI-PC', 'CODX', 'COE', 'COEP', 'COEPW', 'COF', 'COF-PI', 'COF-PJ', 'COF-PK', 'COF-PL', 'COF-PN', 'COFS', 'COGT', 'COHN', 'COHR', 'COHU', 'COIN', 'COKE', 'COLB', 'COLD', 'COLL', 'COLM', 'COMM', 'COMP', 'CONE', 'CONN', 'CONXW', 'COO', 'COOK', 'COOLU', 'COOP', 'COOT', 'COP', 'COR', 'CORR', 'CORR-PA', 'CORT', 'CORZ', 'CORZW', 'CORZZ', 'COSM', 'COST', 'COTY', 'COUP', 'COUR', 'COWN', 'COYA', 'CP', 'CPA', 'CPAC', 'CPARU', 'CPARW', 'CPAY', 'CPB', 'CPBI', 'CPE', 'CPF', 'CPG', 'CPHC', 'CPHI', 'CPIX', 'CPK', 'CPLP', 'CPNG', 'CPOP', 'CPRI', 'CPRT', 'CPRX', 'CPS', 'CPSI', 'CPSS', 'CPT', 'CPTA', 'CPUH-UN', 'CQP', 'CR', 'CRAI', 'CRBG', 'CRBP', 'CRBU', 'CRC', 'CRCT', 'CRD-A', 'CRD-B', 'CRDF', 'CRDL', 'CRDO', 'CREE', 'CREG', 'CRESW', 'CRESY', 'CRGE', 'CRGX', 'CRGY', 'CRH', 'CRHC', 'CRI', 'CRIS', 'CRK', 'CRL', 'CRM', 'CRMD', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CROX', 'CRS', 'CRSAW', 'CRSP', 'CRSR', 'CRTO', 'CRUS', 'CRVL', 'CRVO', 'CRVS', 'CRWD', 'CRWS', 'CRY', 'CS', 'CSAN', 'CSBR', 'CSCO', 'CSCW', 'CSGP', 'CSGS', 'CSII', 'CSIQ', 'CSL', 'CSLR', 'CSLRW', 'CSLT', 'CSOD', 'CSPI', 'CSPR', 'CSR', 'CSSE', 'CSSEL', 'CSSEN', 'CSSEP', 'CSTE', 'CSTL', 'CSTR', 'CSU', 'CSV', 'CSW', 'CSWC', 'CSWI', 'CSX', 'CTA-PB', 'CTAQW', 'CTAS', 'CTBB', 'CTDD', 'CTEV', 'CTGO', 'CTHR', 'CTIB', 'CTIC', 'CTKB', 'CTLP', 'CTLT', 'CTM', 'CTMX', 'CTNT', 'CTO', 'CTOR', 'CTOS', 'CTRA', 'CTRE', 'CTRN', 'CTS', 'CTSH', 'CTSO', 'CTT', 'CTV', 'CTVA', 'CTXR', 'CTXRW', 'CTXS', 'CUBB', 'CUBE', 'CUBI', 'CUBI-PE', 'CUBI-PF', 'CUE', 'CUK', 'CULP', 'CURI', 'CURIW', 'CURR', 'CURV', 'CUTR', 'CUZ', 'CVAC', 'CVBF', 'CVCO', 'CVCY', 'CVE', 'CVEO', 'CVGI', 'CVGW', 'CVI', 'CVLG', 'CVLT', 'CVLY', 'CVM', 'CVNA', 'CVRX', 'CVS', 'CVT', 'CVV', 'CVX', 'CW', 'CWAN', 'CWBC', 'CWBR', 'CWCO', 'CWEN', 'CWEN-A', 'CWH', 'CWK', 'CWST', 'CWT', 'CX', 'CXAIW', 'CXDO', 'CXM', 'CXP', 'CXT', 'CXW', 'CYBE', 'CYBN', 'CYBR', 'CYCC', 'CYCCP', 'CYCN', 'CYD', 'CYH', 'CYRN', 'CYRX', 'CYT', 'CYTH', 'CYTK', 'CYTO', 'CZFS', 'CZNC', 'CZR', 'CZWI', 'D', 'DAC', 'DADA', 'DAIO', 'DAKT', 'DAL', 'DALN', 'DAN', 'DAO', 'DAR', 'DARE', 'DASH', 'DATS', 'DAVA', 'DAVE', 'DAVEW', 'DAWN', 'DAY', 'DB', 'DBD', 'DBGIW', 'DBI', 'DBRG', 'DBRG-PH', 'DBRG-PI', 'DBRG-PJ', 'DBVT', 'DBX', 'DC', 'DC-WT', 'DCBO', 'DCFC', 'DCFCW', 'DCGO', 'DCGOW', 'DCI', 'DCO', 'DCOM', 'DCOMP', 'DCP-PB', 'DCRBU', 'DCRCW', 'DCRNU', 'DCRNW', 'DCT', 'DCTH', 'DCUE', 'DD', 'DDD', 'DDI', 'DDL', 'DDMXW', 'DDOG', 'DDS', 'DE', 'DEA', 'DEC', 'DECA', 'DECK', 'DEFT', 'DEH', 'DEI', 'DELL', 'DEN', 'DENN', 'DEO', 'DERM', 'DESP', 'DFH', 'DFIN', 'DFLI', 'DFS', 'DFSC', 'DG', 'DGHI', 'DGICA', 'DGII', 'DGLY', 'DGNU', 'DGNX', 'DGX', 'DGXX', 'DH', 'DHACW', 'DHC', 'DHCNL', 'DHHCU', 'DHHCW', 'DHI', 'DHIL', 'DHR', 'DHT', 'DHX', 'DICE', 'DIN', 'DINO', 'DIOD', 'DIS', 'DISCA', 'DISCK', 'DISH', 'DIT', 'DJCO', 'DK', 'DKL', 'DKNG', 'DKS', 'DLA', 'DLB', 'DLHC', 'DLNG', 'DLNG-PA', 'DLNG-PB', 'DLO', 'DLPN', 'DLR', 'DLR-PJ', 'DLR-PK', 'DLR-PL', 'DLTH', 'DLTR', 'DLX', 'DM', 'DMAC', 'DMAQ', 'DMF', 'DMLP', 'DMRC', 'DMTK', 'DNA', 'DNB', 'DNLI', 'DNN', 'DNOW', 'DNTH', 'DNUT', 'DO', 'DOC', 'DOCN', 'DOCS', 'DOCU', 'DOGZ', 'DOLE', 'DOMA', 'DOMH', 'DOMO', 'DOOO', 'DOOR', 'DORM', 'DOUG', 'DOV', 'DOW', 'DOX', 'DOYU', 'DPRO', 'DPSI', 'DPW', 'DPZ', 'DQ', 'DRCT', 'DRD', 'DRE', 'DRH', 'DRH-PA', 'DRI', 'DRIO', 'DRNA', 'DRQ', 'DRRX', 'DRS', 'DRTS', 'DRUG', 'DRVN', 'DS', 'DSEY', 'DSGN', 'DSGR', 'DSGX', 'DSKE', 'DSP', 'DSSI', 'DSWL', 'DSX', 'DSY', 'DT', 'DTB', 'DTC', 'DTCK', 'DTE', 'DTG', 'DTI', 'DTIL', 'DTLA-P', 'DTM', 'DTP', 'DTSS', 'DTSTW', 'DTW', 'DTY', 'DUK', 'DUK-PA', 'DUKB', 'DUOL', 'DUOT', 'DV', 'DVA', 'DVAX', 'DVN', 'DWAC', 'DWSN', 'DWTX', 'DX', 'DX-PC', 'DXC', 'DXCM', 'DXPE', 'DXR', 'DY', 'DYN', 'DYNS', 'E', 'EA', 'EACPW', 'EAF', 'EAI', 'EAR', 'EARN', 'EARS', 'EAT', 'EB', 'EBAY', 'EBC', 'EBF', 'EBIX', 'EBMT', 'EBON', 'EBR', 'EBR-B', 'EBS', 'EBTC', 'EC', 'ECBK', 'ECC-PD', 'ECCC', 'ECCV', 'ECCX', 'ECDA', 'ECO', 'ECOL', 'ECOM', 'ECOR', 'ECPG', 'ECVT', 'ED', 'EDAP', 'EDIT', 'EDN', 'EDR', 'EDRY', 'EDSA', 'EDTK', 'EDTXU', 'EDU', 'EE', 'EEFT', 'EEX', 'EFC', 'EFC-PA', 'EFC-PE', 'EFOI', 'EFSC', 'EFSCP', 'EFSI', 'EFX', 'EFXT', 'EG', 'EGAN', 'EGBN', 'EGIO', 'EGLX', 'EGO', 'EGOX', 'EGP', 'EGY', 'EH', 'EHAB', 'EHC', 'EHGO', 'EHTH', 'EIC', 'EICB', 'EIG', 'EIGR', 'EIIA', 'EIX', 'EJH', 'EKSO', 'EL', 'ELA', 'ELAN', 'ELAT', 'ELBM', 'ELC', 'ELDN', 'ELEV', 'ELF', 'ELIQ', 'ELMD', 'ELME', 'ELP', 'ELPW', 'ELS', 'ELTK', 'ELUT', 'ELV', 'ELVN', 'ELVT', 'ELY', 'ELYM', 'EMA', 'EMAN', 'EMBC', 'EMBKW', 'EME', 'EML', 'EMLDW', 'EMN', 'EMP', 'EMPG', 'EMR', 'EMX', 'ENB', 'ENBL', 'ENDP', 'ENFN', 'ENGN', 'ENIC', 'ENLC', 'ENLT', 'ENLV', 'ENO', 'ENOB', 'ENPH', 'ENR', 'ENS', 'ENSC', 'ENSG', 'ENTA', 'ENTG', 'ENTO', 'ENTX', 'ENV', 'ENVA', 'ENVB', 'ENVX', 'EOCW', 'EOG', 'EOLS', 'EOSE', 'EOSEW', 'EP', 'EPAC', 'EPAM', 'EPAY', 'EPC', 'EPD', 'EPIX', 'EPM', 'EPOW', 'EPR', 'EPR-PC', 'EPR-PE', 'EPR-PG', 'EPRT', 'EPRX', 'EPSM', 'EPSN', 'EPWK', 'EPZM', 'EQ', 'EQBK', 'EQC-PD', 'EQH', 'EQH-PA', 'EQH-PC', 'EQIX', 'EQNR', 'EQOS', 'EQR', 'EQRX', 'EQT', 'EQX', 'ERAS', 'ERESW', 'ERF', 'ERIC', 'ERIE', 'ERII', 'ERJ', 'ERNA', 'ERO', 'ES', 'ESAB', 'ESBA', 'ESCA', 'ESE', 'ESEA', 'ESGR', 'ESGRO', 'ESGRP', 'ESI', 'ESLA', 'ESLT', 'ESMT', 'ESNT', 'ESOA', 'ESP', 'ESPR', 'ESQ', 'ESRT', 'ESS', 'ESSA', 'ESSCR', 'ESTA', 'ESTC', 'ESTE', 'ET', 'ET-PC', 'ET-PD', 'ET-PE', 'ETD', 'ETI-P', 'ETN', 'ETNB', 'ETON', 'ETR', 'ETRN', 'ETSY', 'ETTX', 'ETWO', 'ETWO-WT', 'EU', 'EUCRW', 'EUDA', 'EURN', 'EVA', 'EVAX', 'EVBG', 'EVBN', 'EVC', 'EVCM', 'EVER', 'EVEX', 'EVGN', 'EVGO', 'EVGOW', 'EVGR', 'EVH', 'EVI', 'EVK', 'EVLV', 'EVLVW', 'EVO', 'EVOK', 'EVOP', 'EVR', 'EVRG', 'EVRI', 'EVTC', 'EVTL', 'EVTV', 'EW', 'EWBC', 'EWCZ', 'EWTX', 'EXAI', 'EXAS', 'EXC', 'EXE', 'EXEL', 'EXFO', 'EXFY', 'EXLS', 'EXOD', 'EXOZ', 'EXP', 'EXPD', 'EXPE', 'EXPI', 'EXPO', 'EXPR', 'EXR', 'EXTN', 'EXTR', 'EYE', 'EYEG', 'EYEN', 'EYES', 'EYESW', 'EYPT', 'EZFL', 'EZGO', 'EZPW', 'F', 'F-PB', 'F-PC', 'F-PD', 'FA', 'FAAS', 'FAF', 'FAII', 'FANG', 'FANH', 'FARM', 'FARO', 'FAST', 'FAT', 'FATBB', 'FATBP', 'FATBW', 'FATE', 'FATH', 'FATN', 'FBC', 'FBHS', 'FBIN', 'FBIO', 'FBIOP', 'FBIZ', 'FBK', 'FBLA', 'FBMS', 'FBNC', 'FBP', 'FBRT', 'FBRT-PE', 'FBRX', 'FBYD', 'FC', 'FCAP', 'FCBC', 'FCCO', 'FCCY', 'FCEL', 'FCF', 'FCFS', 'FCN', 'FCNCA', 'FCNCO', 'FCNCP', 'FCPT', 'FCRD', 'FCUV', 'FCX', 'FDBC', 'FDMT', 'FDP', 'FDS', 'FDUS', 'FDUSG', 'FDX', 'FE', 'FEAM', 'FEDU', 'FEIM', 'FELE', 'FEMY', 'FENC', 'FENG', 'FER', 'FERG', 'FET', 'FEYE', 'FF', 'FFAI', 'FFBC', 'FFIC', 'FFIE', 'FFIEW', 'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FG', 'FGBI', 'FGBIP', 'FGEN', 'FGF', 'FGFPP', 'FGH', 'FGN', 'FHB', 'FHI', 'FHN', 'FHN-PB', 'FHN-PC', 'FHN-PD', 'FHN-PE', 'FHN-PF', 'FHTX', 'FI', 'FIBK', 'FICO', 'FIEE', 'FIGS', 'FIHL', 'FINV', 'FINW', 'FIP', 'FIS', 'FISI', 'FITB', 'FITBI', 'FITBO', 'FITBP', 'FIVE', 'FIVN', 'FIX', 'FIZZ', 'FKWL', 'FL', 'FLAG', 'FLDDW', 'FLDM', 'FLEX', 'FLG', 'FLGC', 'FLGT', 'FLIC', 'FLJ', 'FLL', 'FLMN', 'FLNC', 'FLNG', 'FLO', 'FLR', 'FLS', 'FLUT', 'FLUX', 'FLX', 'FLXS', 'FLYE', 'FLYW', 'FLYX', 'FLYX-WT', 'FMAO', 'FMBH', 'FMBI', 'FMBIP', 'FMC', 'FMNB', 'FMS', 'FMTX', 'FMX', 'FN', 'FNA', 'FNB', 'FNB-PE', 'FNCB', 'FND', 'FNF', 'FNGR', 'FNKO', 'FNLC', 'FNV', 'FNWB', 'FNWD', 'FOA', 'FOCS', 'FOE', 'FOLD', 'FONR', 'FOR', 'FORA', 'FORG', 'FORM', 'FORR', 'FORTY', 'FOSL', 'FOUR', 'FOX', 'FOXA', 'FOXF', 'FOXWW', 'FPAY', 'FPH', 'FPI', 'FR', 'FRAF', 'FRBA', 'FRBK', 'FRC', 'FRC-PH', 'FRC-PI', 'FRC-PJ', 'FRC-PK', 'FRC-PL', 'FRC-PM', 'FRC-PN', 'FRD', 'FREE', 'FREEW', 'FREQ', 'FRES', 'FREY', 'FREY-WT', 'FRG', 'FRGAP', 'FRGE', 'FRGI', 'FRHC', 'FRLN', 'FRME', 'FRO', 'FROG', 'FRPH', 'FRPT', 'FRSH', 'FRST', 'FRSX', 'FRT', 'FRT-PC', 'FRTA', 'FRTX', 'FSBC', 'FSBW', 'FSCO', 'FSFG', 'FSI', 'FSK', 'FSLR', 'FSLY', 'FSM', 'FSP', 'FSR', 'FSS', 'FSTR', 'FSTX', 'FSUN', 'FSV', 'FTAI', 'FTAIM', 'FTAIN', 'FTAIO', 'FTAIP', 'FTCH', 'FTCI', 'FTCVW', 'FTDR', 'FTEK', 'FTEL', 'FTHM', 'FTI', 'FTK', 'FTLF', 'FTNT', 'FTRE', 'FTS', 'FTSI', 'FTV', 'FUBO', 'FUL', 'FULC', 'FULT', 'FULTP', 'FUN', 'FUNC', 'FURY', 'FUSN', 'FUTU', 'FUV', 'FVCB', 'FVE', 'FVRR', 'FWBI', 'FWONA', 'FWONK', 'FWP', 'FWRD', 'FWRG', 'FXNC', 'FYBR', 'FZT-WT', 'G', 'GABC', 'GAIA', 'GAIN', 'GAINZ', 'GALT', 'GAM', 'GAM-PB', 'GAMB', 'GAME', 'GAN', 'GANX', 'GAP', 'GASS', 'GATO', 'GATX', 'GB', 'GBCI', 'GBDC', 'GBFH', 'GBIO', 'GBL', 'GBLI', 'GBT', 'GBTG', 'GBX', 'GCBC', 'GCL', 'GCMG', 'GCMGW', 'GCO', 'GCP', 'GCTK', 'GCTS', 'GD', 'GDC', 'GDDY', 'GDEN', '

In [8]:
from strategy.factor import MomentumFactor

In [9]:
# 实例化类
mf = MomentumFactor()  # 参数可按你的实际需求传递

# 调用因子函数，获取前10个动量股票
symbols = mf.compute_momentum(days=5, top_n=10, industry=["Asset Management"])
print(symbols)

['PHCF', 'PHCF', 'PHCF', 'PHCF', 'PHCF', 'PCPC-WT', 'SKYAW', 'CLIM-WT', 'SKYAW', 'SKYAW']

In [1]:
from jinja2 import Environment, FileSystemLoader

# 构造测试数据
stock_selection = {
    "numberOfStocks": 5,
    "selectedIndustries": ["Tech", "Finance"],
    "maxIndustryExposure": 0.3
}
factors = [
    {"name": "momentum", "weight": 0.5, "code": "score = calc_momentum(data)"},
    {"name": "pe_ratio", "weight": 0.5, "code": "score = calc_pe(data)"}
]

env = Environment(loader=FileSystemLoader("templates"))
template = env.get_template("strategy_selector.jinja")
rendered = template.render(stock_selection=stock_selection, factors=factors)

print(rendered)

# 选股参数
number_of_stocks = 5
selected_industries = [

    "Tech",

    "Finance",

]
max_industry_exposure = 0.3


# 选股逻辑示例（可根据实际需求替换）
selected_stocks = []

# 应用因子: momentum
score = calc_momentum(data)

# 应用因子: pe_ratio
score = calc_pe(data)


# 行业筛选与限制（伪代码）
# selected_stocks = [s for s in all_stocks if s.industry in selected_industries]
# 限制每个行业最大持仓比例
# ...（具体逻辑可根据 max_industry_exposure 实现）

# 最终选出 number_of_stocks 个股票
# selected_stocks =

In [2]:

import requests

url = "http://localhost:8000/stock_selection"
payload = {
    "numberOfStocks": 10,
    "selectedIndustries": ["Advertising Agencies", "Airlines"],
    "maxIndustryExposure": 50.0
}
resp = requests.post(url, json=payload)
print(resp.text)

Internal Server Error

In [2]:
import requests

url = "http://localhost:8000/stock_selection"
payload = {
    "numberOfStocks": 10,
    "selectedIndustries": ["Advertising Agencies", "Airlines"],
    "maxIndustryExposure": 50.0
}
resp = requests.post(url, json=payload)
print(resp.text)

Internal Server Error

In [4]:
import requests

url = "http://localhost:8000/portfolio_constraint"
payload = {
    "rebalanceFreq": "monthly",
    "maxPositionPerChase": 10,
    "riskFreeRatio": 0.0,
    "positionLimit": 20,
    "commission": 0.1,
    "slip": 0.05
}
resp = requests.post(url, json=payload)
print(resp.text)

Internal Server Error

In [ ]:
import requests

url = "http://localhost:8000/factors/compute"
payload = {
    "factor_keys": ["mom_12m", "gross_margin"],
    "tickers": ["AAPL", "MSFT"],
    "start": "2024-01-01",
    "end": "2024-12-31"
}
resp = requests.post(url, json=payload)
print(resp.json())

In [2]:
import pandas as pd

df = pd.read_parquet(r"d:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet")
print(df.head(100))  # 只看前100行

FileNotFoundError: [Errno 2] No such file or directory: 'd:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet'

In [5]:
import pyarrow.parquet as pq
table = pq.read_table("d:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet", columns=None)
df = table.to_pandas().head(100)
print(df)

FileNotFoundError: d:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet

In [6]:
import duckdb
df = duckdb.query("SELECT * FROM 'merged_data_final.parquet' LIMIT 100").to_df()
print(df)

ModuleNotFoundError: No module named 'duckdb'

In [5]:
import pandas as pd

df = pd.read_parquet(r"d:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet")
print(df.shape)
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'd:/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_data_final.parquet'

In [4]:
from pathlib import Path

file_path = Path(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\new_engine_starter\src\ultimate_data\merged_data_final.parquet")
print(file_path.exists())

True

In [2]:
import pandas as pd

df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\new_engine_starter\src\ultimate_data\merged_data_final.parquet")
df['date'] = pd.to_datetime(df['date'])

# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())

print(df.shape)
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\desktop\\practice_dom\\FINSHARK\\Alpha-Deputy\\fork-zipline\\new_engine_starter\\src\\ultimate_data\\merged_data_final.parquet'

In [7]:
import pandas as pd

df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\all_stocks_full.parquet")
df['date'] = pd.to_datetime(df['date'])
# 输出最小和最大日期

df.head()


# print("检查 symbol 是否有缺失")
# print(df["symbol"].isna().sum())
# # print(df[df["symbol"].isna()])
# # print(df["symbol"].value_counts(dropna=False))

  symbol       date    open    high     low   close      volume  dividend  split_ratio  is_actual_data
0    XYZ 2020-08-06     NaN     NaN     NaN     NaN         NaN       NaN          NaN           False
1    XYZ 2020-08-07     NaN     NaN     NaN     NaN         NaN       NaN          NaN           False
2    XYZ 2020-08-08     NaN     NaN     NaN     NaN         NaN       NaN          NaN           False
3    XYZ 2020-08-09     NaN     NaN     NaN     NaN         NaN       NaN          NaN           False
4    XYZ 2020-08-10  147.53  147.82  138.66  139.34  13196532.0       0.0          1.0            True

In [5]:
print(df[df["symbol"].isna()])
print(df["symbol"].value_counts(dropna=False))

Empty DataFrame
Columns: [symbol, date, open, high, low, close, volume, dividend, split_ratio, is_actual_data]
Index: []
symbol
AFTR-WT    1831
XYZ        1831
FXCOW      1831
MPRAW      1831
MCLDW      1831
           ...
NVR        1831
QBTS       1831
MS         1831
PINS       1831
GDDY       1831
Name: count, Length: 11154, dtype: int64

In [10]:
print(df["symbol"].unique()[:20])  # 看前20个唯一值

print("symbol 长度分布")

print(df["symbol"].str.len().value_counts())  # 看长度分布
# 打印 symbol 长度为 8 的前 10 个
print(df[df["symbol"].str.len() == 8]["symbol"].unique()[:10])
# 打印 symbol 长度为 8 的前 10 行数据
print(df[df["symbol"].str.len() == 8].head(10))

['XYZ' 'SMR' 'GDDY' 'PINS' 'MS' 'QBTS' 'NVR' 'PG' 'MRK' 'BRK-A' 'NEUE'
 'WTM' 'BSBR' 'DUKB' 'NTZ' 'APLE' 'IIPR' 'SII' 'ALUR' 'DY']
symbol 长度分布
symbol
4    10297544
5     4227779
3     3901861
7      725076
6      681132
2      545638
1       40282
8        3662
Name: count, dtype: int64
['OUST-WTA' 'SATX-WTA']
            symbol       date  open  high  low  close  volume  dividend  split_ratio  is_actual_data
13803909  OUST-WTA 2020-08-06   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803910  OUST-WTA 2020-08-07   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803911  OUST-WTA 2020-08-08   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803912  OUST-WTA 2020-08-09   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803913  OUST-WTA 2020-08-10   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803914  OUST-WTA 2020-08-11   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803915  OUST-WTA 2020-08-12   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803916  OUST-WTA 2020-08-13   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803917  OUST-WTA 2020-08-14   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False
13803918  OUST-WTA 2020-08-15   NaN   NaN  NaN    NaN     NaN       NaN          NaN           False

In [8]:
print(df["date"].isna().sum())
print(df["date"].dtype)

print(df.duplicated(subset=["symbol", "date"]).sum())

0
datetime64[ns]
0

In [4]:
import pandas as pd
from pandas.tseries.offsets import BDay 

df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\income_statement.parquet")
df['date'] = pd.to_datetime(df['date'])
# 输出最小和最大日期
print("最小日期:", df['filingDate'].min())
print("最大日期:", df['filingDate'].max())
print(df.dtypes)
print(df.shape)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 200)


# 日期转型
df["filingDate"] = pd.to_datetime(df["filingDate"])
df["announce_date"] = df["filingDate"]
df["effective_date"] = df["announce_date"] + BDay(1)

print("👉 effective_date 最小值:", df["effective_date"].min())
print("👉 effective_date 最大值:", df["effective_date"].max())


df.head(10)

最小日期:
最大日期: 2025-08-08
symbol                                             object
date                                       datetime64[ns]
reportedCurrency                                   object
cik                                                object
filingDate                                         object
acceptedDate                                       object
fiscalYear                                         object
period                                             object
revenue                                           float64
costOfRevenue                                     float64
grossProfit                                       float64
researchAndDevelopmentExpenses                    float64
generalAndAdministrativeExpenses                  float64
sellingAndMarketingExpenses                       float64
sellingGeneralAndAdministrativeExpenses           float64
otherExpenses                                     float64
operatingExpenses                                 float64
costAndExpenses                                   float64
netInterestIncome                                 float64
interestIncome                                    float64
interestExpense                                   float64
depreciationAndAmortization                       float64
ebitda                                            float64
ebit                                              float64
nonOperatingIncomeExcludingInterest               float64
operatingIncome                                   float64
totalOtherIncomeExpensesNet                       float64
incomeBeforeTax                                   float64
incomeTaxExpense                                  float64
netIncomeFromContinuingOperations                 float64
netIncomeFromDiscontinuedOperations               float64
otherAdjustmentsToNetIncome                       float64
netIncome                                         float64
netIncomeDeductions                               float64
bottomLineNetIncome                               float64
eps                                               float64
epsDiluted                                        float64
weightedAverageShsOut                             float64
weightedAverageShsOutDil                          float64
dtype: object
(51035, 39)
👉 effective_date 最小值: 1998-07-01 00:00:00
👉 effective_date 最大值: 2025-08-11 00:00:00

  symbol       date reportedCurrency         cik filingDate         acceptedDate fiscalYear period       revenue  costOfRevenue   grossProfit  researchAndDevelopmentExpenses  generalAndAdministrativeExpenses  sellingAndMarketingExpenses  sellingGeneralAndAdministrativeExpenses  otherExpenses  operatingExpenses  costAndExpenses  netInterestIncome  interestIncome  interestExpense  depreciationAndAmortization        ebitda          ebit  nonOperatingIncomeExcludingInterest  operatingIncome  totalOtherIncomeExpensesNet  incomeBeforeTax  incomeTaxExpense  netIncomeFromContinuingOperations  netIncomeFromDiscontinuedOperations  otherAdjustmentsToNetIncome     netIncome  netIncomeDeductions  bottomLineNetIncome    eps  epsDiluted  weightedAverageShsOut  weightedAverageShsOutDil announce_date effective_date
0    XYZ 2024-12-31              USD  0001512673 2025-02-24  2025-02-24 21:17:17       2024     FY  2.412105e+10   1.523202e+10  8.889036e+09                    2.914415e+09                      2.003591e+09                 1.984265e+09                             3.781899e+09   1.300395e+09       7.996709e+09     2.322873e+10         -9302000.0             0.0        9302000.0                  307763000.0  1.345598e+09  1.037835e+09                         -145508000.0      892327000.0                  464827000.0     1.357154e+09     -1.509343e+09                       2.866497e+09                                  0.0                          0.0  2.897047e+09                  0.0         2.897047e+09  4.700      4.5500            616993000.0               636390000.0    2025-02-24     2025-02-25
1    XYZ 2023-12-31              USD  0001512673 2024-02-22  2024-02-22 16:18:13       2023     FY  2.191562e+10   1.441074e+10  7.504886e+09                    2.720819e+09                      2.209190e+09                 2.019009e+09                             4.228199e+09   8.347070e+08       7.783725e+09     2.219446e+10         47221000.0      47221000.0              0.0                  419673000.0  3.905300e+08 -2.914300e+07                         -249696000.0     -278839000.0                  249696000.0    -2.914300e+07     -8.019000e+06                      -2.112400e+07                                  0.0                          0.0  9.772000e+06                  0.0         9.772000e+06  0.016      0.0159            608856000.0               614024000.0    2024-02-22     2024-02-23
2    XYZ 2022-12-31              USD  0001512673 2023-02-23  2023-02-23 16:23:08       2022     FY  1.753159e+10   1.153970e+10  5.991892e+09                    2.135612e+09                      1.686849e+09                 2.057951e+09                             3.744800e+09   6.894410e+08       6.569853e+09     1.810955e+10        -36228000.0             0.0       36228000.0                  470334000.0 -5.875500e+07 -5.290890e+08                          -95443000.0     -624532000.0                   59215000.0    -5.653170e+08     -1.231200e+07                      -5.530050e+08                                  0.0                          0.0 -5.407470e+08                  0.0        -5.407470e+08 -0.930     -0.9300            578949000.0               578949000.0    2023-02-23     2023-02-24
3    XYZ 2021-12-31              USD  0001512673 2022-02-24  2022-02-24 16:19:13       2021     FY  1.766120e+10   1.324138e+10  4.419823e+09                    1.399079e+09                      9.833260e+08                 1.617189e+09                             2.600515e+09   1.879910e+08       4.187585e+09     1.742896e+10        -33124000.0             0.0       33124000.0                  217893000.0  4.084790e+08  1.905860e+08                          -29474000.0      161112000.0                   -3650000.0     1.574620e+08     -1.364000e+06                       1.588260e+08                                  0.0                          0.0  1.662840e+08                  0.0         1.662840e+08  0.360      0.3300            458432000.0               501779000.0    2022-02-24     2022-02-25
4    XYZ 2020-12-31              USD  0001512673 2021-02-23  2021-02-23 16:19:48       2020     FY  9.497578e+09   6.764169e+09  2.733409e+09                    8.818260e+08                      5.792030e+08                 1.109670e+09                             1.688873e+09   1.815250e+08       2.752224e+09     9.516393e+09        -56943000.0             0.0       56943000.0                  154465000.0  4.273750e+08  2.729100e+08                                  0.0      272910000.0                  234782000.0     2.159670e+08      2.862000e+06                       2.131050e+08                                  0.0                          0.0  2.131050e+08                  0.0         2.131050e+08  0.480      0.4400            443126000.0               482167000.0    2021-02-23     2021-02-24
5    SMR 2024-12-31              USD  0001822966 2025-03-03  2025-03-03 17:25:16       2024     FY  3.704500e+07   4.937000e+06  3.210800e+07                    4.681700e+07                      7.590100e+07                 0.000000e+00                             7.590100e+07   4.811500e+07       1.708330e+08     1.757700e+08          8388000.0       8388000.0              0.0                    1842000.0 -1.368830e+08 -1.387250e+08                                  0.0     -138725000.0                 -207727000.0    -3.464520e+08      1.935000e+06                      -3.483870e+08                                  0.0                          0.0 -1.366230e+08                  0.0        -1.366230e+08 -1.470     -1.4700             93250000.0                93250000.0    2025-03-03     2025-03-04
6    SMR 2023-12-31              USD  0001822966 2024-03-15  2024-03-15 17:04:41       2023     FY  2.281000e+07   1.896100e+07  3.849000e+06                    1.560500e+08                      6.540400e+07                 0.000000e+00                             6.540400e+07   5.796000e+07       2.794140e+08     2.983750e+08         10792000.0      10792000.0              0.0                    2557000.0 -2.730080e+08 -2.755650e+08                                  0.0     -275565000.0                   95450000.0    -1.801150e+08      0.000000e+00                      -1.801150e+08                                  0.0                          0.0 -5.836200e+07                  0.0        -5.836200e+07 -0.800     -0.8000             73386018.0                73386018.0    2024-03-15     2024-03-18
7    SMR 2022-12-31              USD  0001822966 2023-03-16  2023-03-15 17:37:02       2022     FY  1.180400e+07   7.317000e+06  4.487000e+06                    1.234160e+08                      6.305700e+07                 0.000000e+00                             6.305700e+07   4.800900e+07       2.344820e+08     2.417990e+08          3760000.0       3760000.0              0.0                    2698000.0 -2.272970e+08 -2.299950e+08                                  0.0     -229995000.0                   88422000.0    -1.415730e+08      0.000000e+00                      -1.415730e+08                          -53349000.0                   84504000.0 -2.591400e+07                  0.0        -2.591400e+07 -0.510     -0.5100             50763844.0                50763844.0    2023-03-16     2023-03-17
8    SMR 2021-12-31              USD  0001822966 2022-03-10  2022-03-10 17:16:36       2021     FY  2.862000e+06   1.770000e+06  1.092000e+06                    9.313600e+07                      4.522600e+07                 0.000000e+00                             4.522600e+07   3.703000e+07       1.753920e+08     1.771620e+08         -1715000.0       1715000.0        1715000.0                    2195000.0 -1.721050e+08 -1.743000e+08                                  0.0     -174300000.0                   71807000.0    -1.024930e+08      0.000000e+00                      -1.024930e+08                                  0.0                          0.0 -1.024930e+08                  0.0        -1.024930e+08 -2.350     -2.3500             43615304.0                43615304.0    2022-03-10     2022-03-11
9    SMR 2020-12-31              USD  0001822966 2021-03-31  2021-03-31 14:06:50       2020     FY  6.000000e+05   3.550000e+05  2.450000e+05                    9.526700e+07                      3.717600e+07                 0.000000e+00                             3.717600e+07   2.664500e+07       1.590880e+08     1.594430e+08          -653000.0          1973.0         653000.0                    2078000.0 -1.567650e+08 -1.588430e+08                                  0.0     -158843000.0                   70456000.0    -8.838700e+07      0.000000e+00                      -8.838700e+07                                  0.0                          0.0 -8.838700e+07          -75415576.0        -8.838700e+07 -2.030     -2.0300             43615304.0                43615304.0    2021-03-31     2021-04-01

In [8]:
import pandas as pd

df = pd.read_parquet(r"d:/desktop/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_ultimate_with_flag.parquet")
df['date'] = pd.to_datetime(df['date'])
# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())
print(df.dtypes)
print(df.shape)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 200)  
df.head(10)

最小日期: 2020-08-06 00:00:00
最大日期: 2022-12-31 00:00:00
date                                       datetime64[ns]
symbol                                             object
open                                              float64
high                                              float64
low                                               float64
close                                             float64
volume                                            float64
effective_date                             datetime64[ns]
period_end                                 datetime64[ns]
reportedCurrency                                   object
cik                                                object
acceptedDate                                       object
fiscalYear                                         object
period                                             object
revenue                                           float64
costOfRevenue                                     float64
grossProfit                                       float64
researchAndDevelopmentExpenses                    float64
generalAndAdministrativeExpenses                  float64
sellingAndMarketingExpenses                       float64
sellingGeneralAndAdministrativeExpenses           float64
otherExpenses                                     float64
operatingExpenses                                 float64
costAndExpenses                                   float64
netInterestIncome                                 float64
interestIncome                                    float64
interestExpense                                   float64
depreciationAndAmortization                       float64
ebitda                                            float64
ebit                                              float64
nonOperatingIncomeExcludingInterest               float64
operatingIncome                                   float64
totalOtherIncomeExpensesNet                       float64
incomeBeforeTax                                   float64
incomeTaxExpense                                  float64
netIncomeFromContinuingOperations                 float64
netIncomeFromDiscontinuedOperations               float64
otherAdjustmentsToNetIncome                       float64
netIncome                                         float64
netIncomeDeductions                               float64
bottomLineNetIncome                               float64
eps                                               float64
epsDiluted                                        float64
weightedAverageShsOut                             float64
weightedAverageShsOutDil                          float64
is_actual_data                                       bool
dtype: object
(9791456, 46)

        date symbol  open  high  low  close  volume effective_date period_end reportedCurrency   cik acceptedDate fiscalYear period  revenue  costOfRevenue  grossProfit  researchAndDevelopmentExpenses  generalAndAdministrativeExpenses  sellingAndMarketingExpenses  sellingGeneralAndAdministrativeExpenses  otherExpenses  operatingExpenses  costAndExpenses  netInterestIncome  interestIncome  interestExpense  depreciationAndAmortization  ebitda  ebit  nonOperatingIncomeExcludingInterest  operatingIncome  totalOtherIncomeExpensesNet  incomeBeforeTax  incomeTaxExpense  netIncomeFromContinuingOperations  netIncomeFromDiscontinuedOperations  otherAdjustmentsToNetIncome  netIncome  netIncomeDeductions  bottomLineNetIncome  eps  epsDiluted  weightedAverageShsOut  weightedAverageShsOutDil  is_actual_data
0 2020-08-06    XYZ   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
1 2020-08-06    SKE   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
2 2020-08-06   AMPS   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
3 2020-08-06   TSBX   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
4 2020-08-06    EXK   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
5 2020-08-06    TRC   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
6 2020-08-06  MINDP   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
7 2020-08-06   FATP   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
8 2020-08-06  FLFVR   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False
9 2020-08-06   CBRL   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN           False

In [24]:
import pandas as pd
print("查验Income表")
df_income = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\income_statement.parquet")
df_income['date'] = pd.to_datetime(df_income['date'])

# 输出最小和最大日期
print("最小日期:", df_income['filingDate'].min())
print("最大日期:", df_income['filingDate'].max())

print(df_income.shape)
print(df_income.head())

查验Income表
最小日期:
最大日期: 2025-08-08
(51035, 39)
  symbol       date reportedCurrency         cik  filingDate  \
0    XYZ 2024-12-31              USD  0001512673  2025-02-24
1    XYZ 2023-12-31              USD  0001512673  2024-02-22
2    XYZ 2022-12-31              USD  0001512673  2023-02-23
3    XYZ 2021-12-31              USD  0001512673  2022-02-24
4    XYZ 2020-12-31              USD  0001512673  2021-02-23

          acceptedDate fiscalYear period       revenue  costOfRevenue  ...  \
0  2025-02-24 21:17:17       2024     FY  2.412105e+10   1.523202e+10  ...
1  2024-02-22 16:18:13       2023     FY  2.191562e+10   1.441074e+10  ...
2  2023-02-23 16:23:08       2022     FY  1.753159e+10   1.153970e+10  ...
3  2022-02-24 16:19:13       2021     FY  1.766120e+10   1.324138e+10  ...
4  2021-02-23 16:19:48       2020     FY  9.497578e+09   6.764169e+09  ...

   netIncomeFromContinuingOperations  netIncomeFromDiscontinuedOperations  \
0                       2.866497e+09                                  0.0
1                      -2.112400e+07                                  0.0
2                      -5.530050e+08                                  0.0
3                       1.588260e+08                                  0.0
4                       2.131050e+08                                  0.0

   otherAdjustmentsToNetIncome     netIncome  netIncomeDeductions  \
0                          0.0  2.897047e+09                  0.0
1                          0.0  9.772000e+06                  0.0
2                          0.0 -5.407470e+08                  0.0
3                          0.0  1.662840e+08                  0.0
4                          0.0  2.131050e+08                  0.0

   bottomLineNetIncome    eps  epsDiluted  weightedAverageShsOut  \
0         2.897047e+09  4.700      4.5500            616993000.0
1         9.772000e+06  0.016      0.0159            608856000.0
2        -5.407470e+08 -0.930     -0.9300            578949000.0
3         1.662840e+08  0.360      0.3300            458432000.0
4         2.131050e+08  0.480      0.4400            443126000.0

   weightedAverageShsOutDil
0               636390000.0
1               614024000.0
2               578949000.0
3               501779000.0
4               482167000.0

[5 rows x 39 columns]

In [ ]:
import pandas as pd

# 读取 parquet 文件
df = pd.read_parquet("path/to/all_stocks.parquet")

# 确保 date 字段是 datetime 类型

In [16]:
import pandas as pd

df = pd.read_parquet(r"d:/desktop/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_ultimate.parquet")
df['date'] = pd.to_datetime(df['date'])

# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())

print(df.shape)
print(df.head())

print(df["symbol"].nunique())           # symbol 总数
print(df["symbol"].nunique())      # 保留后 symbol 数量是否变少

最小日期: 2020-08-06 00:00:00
最大日期: 2022-12-31 00:00:00
(9791456, 45)
        date symbol  open  high  low  close  volume effective_date period_end  \
0 2020-08-06    XYZ   NaN   NaN  NaN    NaN     NaN            NaT        NaT
1 2020-08-06    SKE   NaN   NaN  NaN    NaN     NaN            NaT        NaT
2 2020-08-06   AMPS   NaN   NaN  NaN    NaN     NaN            NaT        NaT
3 2020-08-06   TSBX   NaN   NaN  NaN    NaN     NaN            NaT        NaT
4 2020-08-06    EXK   NaN   NaN  NaN    NaN     NaN            NaT        NaT

  reportedCurrency  ... netIncomeFromContinuingOperations  \
0             None  ...                               NaN
1             None  ...                               NaN
2             None  ...                               NaN
3             None  ...                               NaN
4             None  ...                               NaN

  netIncomeFromDiscontinuedOperations otherAdjustmentsToNetIncome netIncome  \
0                                 NaN                         NaN       NaN
1                                 NaN                         NaN       NaN
2                                 NaN                         NaN       NaN
3                                 NaN                         NaN       NaN
4                                 NaN                         NaN       NaN

   netIncomeDeductions  bottomLineNetIncome  eps  epsDiluted  \
0                  NaN                  NaN  NaN         NaN
1                  NaN                  NaN  NaN         NaN
2                  NaN                  NaN  NaN         NaN
3                  NaN                  NaN  NaN         NaN
4                  NaN                  NaN  NaN         NaN

   weightedAverageShsOut  weightedAverageShsOutDil
0                    NaN                       NaN
1                    NaN                       NaN
2                    NaN                       NaN
3                    NaN                       NaN
4                    NaN                       NaN

[5 rows x 45 columns]
11152
11152

In [3]:
import pandas as pd

df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\all_stocks_full.parquet")
#df['date'] = pd.to_datetime(df['date'])

# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())

print(df.dtypes)
print(df["symbol"].dtype)



print("查验Income表")
df_01 = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\data\bundles\data\income_statement.parquet")
print("最小日期:", df_01['date'].min())
print("最大日期:", df_01['date'].max())
print(df_01.dtypes)
print(df_01["symbol"].dtype)

最小日期: 2020-08-06 00:00:00
最大日期: 2025-08-10 00:00:00
symbol                    object
date              datetime64[ns]
open                     float64
high                     float64
low                      float64
close                    float64
volume                   float64
dividend                 float64
split_ratio              float64
is_actual_data              bool
dtype: object
object
查验Income表
最小日期:
最大日期: 2025-06-30
symbol                                      object
date                                        object
reportedCurrency                            object
cik                                         object
filingDate                                  object
acceptedDate                                object
fiscalYear                                  object
period                                      object
revenue                                    float64
costOfRevenue                              float64
grossProfit                                float64
researchAndDevelopmentExpenses             float64
generalAndAdministrativeExpenses           float64
sellingAndMarketingExpenses                float64
sellingGeneralAndAdministrativeExpenses    float64
otherExpenses                              float64
operatingExpenses                          float64
costAndExpenses                            float64
netInterestIncome                          float64
interestIncome                             float64
interestExpense                            float64
depreciationAndAmortization                float64
ebitda                                     float64
ebit                                       float64
nonOperatingIncomeExcludingInterest        float64
operatingIncome                            float64
totalOtherIncomeExpensesNet                float64
incomeBeforeTax                            float64
incomeTaxExpense                           float64
netIncomeFromContinuingOperations          float64
netIncomeFromDiscontinuedOperations        float64
otherAdjustmentsToNetIncome                float64
netIncome                                  float64
netIncomeDeductions                        float64
bottomLineNetIncome                        float64
eps                                        float64
epsDiluted                                 float64
weightedAverageShsOut                      float64
weightedAverageShsOutDil                   float64
dtype: object
object

In [15]:
symbols = df["symbol"].unique()
print(len(symbols), symbols[:5])
print(df["symbol"].nunique())
print(df["is_actual_data"].value_counts())

11154 ['XYZ' 'SMR' 'GDDY' 'PINS' 'MS']
11154
is_actual_data
False    11388191
True      9034783
Name: count, dtype: int64

In [9]:
import pandas as pd

df = pd.read_parquet(r"d:\desktop\practice_dom\FINSHARK\Alpha-Deputy\fork-zipline\new_engine_starter\src\ultimate_data\merged_ultimate.parquet")
df['date'] = pd.to_datetime(df['date'])
# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())
print(df.dtypes)
print(df.shape)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 200)  
df.head(10)
print(df.columns.tolist())

最小日期: 2020-08-06 00:00:00
最大日期: 2022-12-31 00:00:00
date                                       datetime64[ns]
symbol                                             object
open                                              float64
high                                              float64
low                                               float64
close                                             float64
volume                                            float64
effective_date                             datetime64[ns]
period_end                                 datetime64[ns]
reportedCurrency                                   object
cik                                                object
acceptedDate                                       object
fiscalYear                                         object
period                                             object
revenue                                           float64
costOfRevenue                                     float64
grossProfit                                       float64
researchAndDevelopmentExpenses                    float64
generalAndAdministrativeExpenses                  float64
sellingAndMarketingExpenses                       float64
sellingGeneralAndAdministrativeExpenses           float64
otherExpenses                                     float64
operatingExpenses                                 float64
costAndExpenses                                   float64
netInterestIncome                                 float64
interestIncome                                    float64
interestExpense                                   float64
depreciationAndAmortization                       float64
ebitda                                            float64
ebit                                              float64
nonOperatingIncomeExcludingInterest               float64
operatingIncome                                   float64
totalOtherIncomeExpensesNet                       float64
incomeBeforeTax                                   float64
incomeTaxExpense                                  float64
netIncomeFromContinuingOperations                 float64
netIncomeFromDiscontinuedOperations               float64
otherAdjustmentsToNetIncome                       float64
netIncome                                         float64
netIncomeDeductions                               float64
bottomLineNetIncome                               float64
eps                                               float64
epsDiluted                                        float64
weightedAverageShsOut                             float64
weightedAverageShsOutDil                          float64
dtype: object
(9791456, 45)
['date', 'symbol', 'open', 'high', 'low', 'close', 'volume', 'effective_date', 'period_end', 'reportedCurrency', 'cik', 'acceptedDate', 'fiscalYear', 'period', 'revenue', 'costOfRevenue', 'grossProfit', 'researchAndDevelopmentExpenses', 'generalAndAdministrativeExpenses', 'sellingAndMarketingExpenses', 'sellingGeneralAndAdministrativeExpenses', 'otherExpenses', 'operatingExpenses', 'costAndExpenses', 'netInterestIncome', 'interestIncome', 'interestExpense', 'depreciationAndAmortization', 'ebitda', 'ebit', 'nonOperatingIncomeExcludingInterest', 'operatingIncome', 'totalOtherIncomeExpensesNet', 'incomeBeforeTax', 'incomeTaxExpense', 'netIncomeFromContinuingOperations', 'netIncomeFromDiscontinuedOperations', 'otherAdjustmentsToNetIncome', 'netIncome', 'netIncomeDeductions', 'bottomLineNetIncome', 'eps', 'epsDiluted', 'weightedAverageShsOut', 'weightedAverageShsOutDil']

In [3]:
import pandas as pd

df = pd.read_parquet(r"d:/desktop/practice_dom/FINSHARK/Alpha-Deputy/fork-zipline/new_engine_starter/src/ultimate_data/merged_ultimate.parquet")
df['date'] = pd.to_datetime(df['date'])

# 输出最小和最大日期
print("最小日期:", df['date'].min())
print("最大日期:", df['date'].max())

print(df.shape)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 200)  
print(df.head())

print(df["symbol"].nunique())           # symbol 总数
print(df["symbol"].nunique())      # 保留后 symbol 数量是否变少

最小日期: 2020-08-06 00:00:00
最大日期: 2022-12-31 00:00:00
(9791456, 45)
        date symbol  open  high  low  close  volume effective_date period_end reportedCurrency   cik acceptedDate fiscalYear period  revenue  costOfRevenue  grossProfit  researchAndDevelopmentExpenses  generalAndAdministrativeExpenses  sellingAndMarketingExpenses  sellingGeneralAndAdministrativeExpenses  otherExpenses  operatingExpenses  costAndExpenses  netInterestIncome  interestIncome  interestExpense  depreciationAndAmortization  ebitda  ebit  nonOperatingIncomeExcludingInterest  operatingIncome  totalOtherIncomeExpensesNet  incomeBeforeTax  incomeTaxExpense  netIncomeFromContinuingOperations  netIncomeFromDiscontinuedOperations  otherAdjustmentsToNetIncome  netIncome  netIncomeDeductions  bottomLineNetIncome  eps  epsDiluted  weightedAverageShsOut  weightedAverageShsOutDil
0 2020-08-06    XYZ   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN
1 2020-08-06    SKE   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN
2 2020-08-06   AMPS   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN
3 2020-08-06   TSBX   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN
4 2020-08-06    EXK   NaN   NaN  NaN    NaN     NaN            NaT        NaT             None  None         None       None   None      NaN            NaN          NaN                             NaN                               NaN                          NaN                                      NaN            NaN                NaN              NaN                NaN             NaN              NaN                          NaN     NaN   NaN                                  NaN              NaN                          NaN              NaN               NaN                                NaN                                  NaN                          NaN        NaN                  NaN                  NaN  NaN         NaN                    NaN                       NaN
11152
11152

ModuleNotFoundError: No module named 'zipline'